name: local-rag

services:
  app:
    build: .
    image: local-rag:latest
    ports:
      - "8501:8501"
    environment:
      - APP_OLLAMA_URL=http://ollama:11434/v1
      # Dev settings
      - APP_DEV_MODE=true
      - APP_DEBUG=true
      - APP_LOG_LEVEL=DEBUG
      - APP_MOCK_LLM=true
      - APP_USE_RAG=false
      - APP_RELOAD=true
    volumes:
      - ./app:/local-rag/app
      - ./ui:/local-rag/ui
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    command: ["bash", "-c", "python -m app.api.main & python -m streamlit run ui/streamlit_app.py --server.address=0.0.0.0"]

  ollama:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    volumes:
      - ${OLLAMA_MODEL_PATH:-~/.ollama}:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test:  "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s